name: Conditional Workflow Execution
on: [push]
jobs:
  production-deploy:
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Check Node.js version
        run: node --version
        with:
          node-version: '14'
